data_ingestion:
  workspace: "roboflow-universe-projects"
  project_name: "license-plate-recognition-rxg4e"
  version: "11"
  format: "voc"

data_validation:
  required_files:
    - train
    - test
    - valid
